server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
logging:
  level:
    root: INFO
    # 配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'
# https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html 官方文档
# 新增配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true