server:
  port: 7000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-ware
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

    #关闭thymeleaf缓存
  thymeleaf:
    cache: false

  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0


logging:
  level:
    org.springframework.web: debug
    com.atguigu.gulimall.coupon.dao: debug


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'