server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=yes&characterEncoding=utf8
    username: root
    password: 123456
  web:
    resources:
      static-locations:


mybatis-plus:
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    root: info
    org:
      springframework:
        web: debug



  pattern:
    console=: "[%X{trade_id}]%date{yyyy-MM-dd HH:mm:ss.SSS} %-5level[%thread]%C{56}.%method:%L %msg%n"

#返回处理内容的
#logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor=INFO


