server:
  port: 8080
spring:
  profiles:
      active: dev
  web:
    resources:
      static-locations:
        - classpath:/sgstatic/
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 58613458
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
logging.level.com.sangeng.mapper: debug
logging:
  level:
    root: info
    org:
      springframework:
        web: debug