spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource