server:
  port: 8081
spring:
  profiles:
    active: dev


---
server:
  port: 8082
  servlet:
    context-path: /kuang
my.hello:
    name: xiaohu
    age: 18

spring:
  profiles: dev

---
server:
  port: 8084
spring:
  profiles: production
