server:
  port: 9999
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: https://github.com/JaredTan95/MicroService-Study-Samples.git
          # Git仓库账号
          username:
          # Git仓库密码
          password: