server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations:
    - classpath:com/ktb/macrozhengmall/**/*.xml
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间


logging.level.org.springframework.web: DEBUG
spring.http.log-request-details: true
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
logging.level.com.ktb.macrozhengmall.dao: DEBUG
#logging.level.org.zalando.logbook: trace