spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&useSSL=false
          username: root
          password: 12345678
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&useSSL=false
          username: root
          password: 12345678
          driver-class-name: com.mysql.cj.jdbc.Driver

logging.level.com.ktb.mybatisplus.mapper: DEBUG


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      # id生成策略 auto为数据库自增
      logic-delete-field: is_delete
      id-type: ASSIGN_ID
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-enums-package: com.ktb.mybatisplus.model.enums