spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newbee_mall_db_v2?characterEncoding=utf-8&useSSL=false
    username: root
    password: 58613458
    driver-class-name: com.mysql.cj.jdbc.Driver

logging.level.com.ktb.newbee.dao: DEBUG
logging:
  level:
    org:
      springframework:
        web: DEBUG


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      logic-delete-field: is_delete
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
